apiVersion: v1
kind: Service
metadata:
  name: todo-ingress
  labels:
    app: todo-ingress
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: todo-ingress
